version: "3.5"

services:
  web:
    image: webdevops/php-nginx:7.4
    working_dir: /app
    ports:
      - 8000:80
    depends_on:
      - database
    volumes:
      - .:/app
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      WEB_DOCUMENT_INDEX: index.php
      PHP_DATE_TIMEZONE: "Europe/Paris"
      PHP_DISPLAY_ERRORS: 1

  database:
    image: mariadb:10.4.11
    ports :
      - 3306:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./sql/import.sql:/docker-entrypoint-initdb.d/import.sql
    environment:
      MYSQL_DATABASE: tptest
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - database
    ports:
      - 8080:80
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: database